# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --builtins="Error" --count --select=E9,F63,F7,F82 --show-source --statistics 
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --builtins="Error" --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run lint program
      run: |
        python ./lint.py
    - name: Run compute program
      run: |
        python ./compute.py > docs/routes.json
    - name: Run ccmap program
      run: |
        export LAST_UPDATE=$(git log --format='%ct' -1 -- data)
        echo $LAST_UPDATE
        python ./ccmap.py > docs/ccmap.json
    - name: Run export program
      run: |
        python ./export.py > docs/export.json
    - name: Commit routes.json to git
      run: |
        git config --local user.name "KANI Bot"
        if ! git diff --quiet --exit-code docs/routes.json; then
        git add docs/routes.json
        git commit -m "Update routes.json"
        fi
    - name: Commit ccmap.json to git
      run: |
        git config --local user.name "KANI Bot"
        if ! git diff --quiet --exit-code docs/ccmap.json; then
        git add docs/ccmap.json
        git commit -m "Update ccmap.json"
        fi
    - name: Commit export.json to git
      run: |
        git config --local user.name "KANI Bot"
        if ! git diff --quiet --exit-code docs/export.json; then
        git add docs/export.json
        git commit -m "Update export.json"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
